import '../entities/entities.dart';
import '../repositories/interfaces.dart';
import '../logic/body_metrics_calculator.dart';

class CalculateAndSaveMetrics {
  final MetricsRepository repository;

  CalculateAndSaveMetrics(this.repository);

  Future<BodyMetrics> execute({
    required String userId,
    required double weight,
    required double height,
    required int age,
    required String gender,
    required String activityLevel,
  }) async {
    final bmi = BodyMetricsCalculator.calculateBMI(weight, height);
    final bodyFat = BodyMetricsCalculator.estimateBodyFat(bmi, age, gender);
    final calorieExp = BodyMetricsCalculator.calculateTDEE(weight, height, age, gender, activityLevel);

    final metrics = BodyMetrics(
      id: '', // Will be generated by DB
      userId: userId,
      weight: weight,
      height: height,
      bmi: bmi,
      bodyFat: bodyFat,
      dailyCalorieExp: calorieExp,
      createdAt: DateTime.now(),
    );

    await repository.saveMetrics(metrics);
    return metrics;
  }
}

class GetHealthyRecommendations {
  final RecommendationRepository repository;

  GetHealthyRecommendations(this.repository);

  Future<List<HealthyRecommendation>> execute(double bmi) {
    return repository.getRecommendations(bmi);
  }
}
